### ISSUE TITLE
--format sdist --no-setup-py could be the default.

### ISSUE THREAD

**Issue by dougransom** [pypa/flit#391]
Pretty much all modern python installations will have a PIP supporting PEP517.  So wouldn't it make more sense in the next release to default to sdist for format with --no-setup-py as a default?

**Comment by takluyver** [comment]
I'm expecting that when I flip that switch, a bunch of people will show up to complain. In particular, I think many downstream packaging systems (Linux distros, Spack, etc.) are used to downloading a tarball and running `python setup.py`, and haven't necessarily been adapted to use PEP 517. In part, this depends on the maturity of tools like [build](https://github.com/pypa/build) and [installer](https://github.com/pradyunsg/installer/), which are designed to be used in this kind of scenario (as opposed to pip, which is designed for end users, so does a bunch of extra stuff which packagers prefer to turn off).

Have you already used `--no-setup-py` on any packages on PyPI? Have you got any pushback for it?

**Comment by dougransom** [comment]
I only use --no-setup-py.  One project only myself and my business partner are known users;  the other is natlink, which had no package till i made one with flit, so i think people are happy they can use PIP at all.  https://gitter.im/dictation-toolbox/natlink

**Comment by dougransom** [comment]
maybe you could add a warning for a year.

**Comment by takluyver** [comment]
Flit 3.4 will have a `--setup-py` option, and a message saying that the default is going to change.

**Comment by takluyver** [comment]
Building sdists without setup.py is now the default behaviour.
