### ISSUE TITLE
[0.15.2] Debian build problem with flit

### ISSUE THREAD

**Issue by olebole** [pypa/flit#436]
Hi,

I just started with upgrading the poliastro package on Debian (from 0.14.0). One change here is the use of flit which is new for me and causes a build failure for the moment: when running flit in the root dir, I get the error message
```
$ flit build
Config error: [tool.flit.metadata] section is required
```
This is also what our automated build does. Do I miss/misunderstand something here? How would I start building?

**Comment by takluyver** [comment]
It looks like poliastro has started using PEP 621 metadata (the `[project]` table), which can be read by flit_core 3.2+. I'm guessing the version in Debian is older than that.

I don't think there's any easy workaround. If you really need to, you could patch the `pyproject.toml` file back to the previous format (basically revert [this commit](https://github.com/poliastro/poliastro/commit/5883dd3f0dd7e1fb12454e40e80a88d0973a18ad#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)). But now that PEP 621 has given us a standard way to specify this metadata, I would imagine that it's going to get adopted by other packages pretty rapidly.

**Comment by nanonyme** [comment]
@takluyve if what you say abut adoption of PEP621 is true, that will most likely result in noise. Debian 11 which was released last Summer has flit 3.0.0. Are there backwards-incompatible changes with 3.2.x that would prevent working on pushing that to Debian stable release?

**Comment by kitterma** [comment]
There are.  Flit 3.3 is available in Debian stable backports now.

**Comment by kitterma** [comment]
Also, for Debian packages, we've integrated use of flit into dh-python.  All you need to do now is package it as you traditionally have for a Debian python package and add flit to build-depends.  It will use the pyproject.toml information automatically.  I'm not sure if the newer PEP 621 stuff works on stable.  It does work on testing/unstable.

**Comment by pradyunsg** [comment]
Closing this out, since @kitterma seems to have made progress on this, on Debian’s side! 🎉
