### ISSUE TITLE
Allow non-HTTP(S) URLs

### ISSUE THREAD

**Issue by McSinyx** [pypa/flit#444]
As neither PEP 621 nor core metadata specification prohibits other scheme, I think restricting to just HTTP or HTTPS is rather too strict:

https://github.com/takluyver/flit/blob/b944ecceabe6c01f45d80c3c4c9160f97829e4c3/flit/validate.py#L239-L248

Context: I was trying to declare a link to a Matrix room with the `matrix:` scheme.

**Comment by McSinyx** [comment]
What's your opinion on this, @takluyver?

**Comment by takluyver** [comment]
PyPI restricts these URLs to http(s) as well: https://github.com/pypi/warehouse/issues/10198 . They also note there that the core metadata spec says 'browsable' URLs, which maybe implies HTTP (though that's debatable). Flit's validation code is largely to catch things early that would get your upload rejected, so as long as PyPI has this restriction, I'd leave it in Flit too. You can use [FLIT_ALLOW_INVALID](https://flit.pypa.io/en/stable/cmdline.html#envvar-FLIT_ALLOW_INVALID) if you have a specific need to build a package that can't be upload.

If PyPI were to relax the restriction, I'd be OK doing the same in Flit, but I'd still want to try to catch cases where you've put a URL like `"www.python.org"`, which can be interpreted as a relative URL ([example](www.python.org)).

**Comment by McSinyx** [comment]
Thanks, I didn't know about that requirement in the core specs.
Should this be closed now?

**Comment by takluyver** [comment]
I think so. I've subscribed to the Warehouse issue, so if there's any change there, I should hear about it.
