### ISSUE TITLE
Question: specify platform compatibility

### ISSUE THREAD

**Issue by karrukola** [pypa/flit#450]
Hello,
thanks for making this tool, first of all.

I am wondering whether there is a way to specify that the distribution package is not suitable for certain OSes. This would reflect in the platform tag as per PEP425. I could not grasp it from the documentation.

The rationale/use case I have for this question is the following example.

A project may use `pexpect.spawn()` that is not supported by Windows. Rather than identifying this problem at execution time it would be better to avoid the installation on Windows in the first place. My understanding is that, as a solution, the wheel should better not indicate `any` in the _Platform Tag_ even though it is a _pure Python_ project.

A couple of additional considerations:
- `pexpect` is delivered for Windows, so the dependency would be installed and the failure identified at runtime
- using an environment marker would prevent the installation of such dependency, but not of the whole package. I.e.
`dependencies = [
    "pexpect; sys_platform != 'win32'",
] `
- _Trove Classifiers_ are not used by installation tools such as `pip`, so that won't help as well

Am I missing anything? Please advise.

Thanks again.

**Comment by takluyver** [comment]
I'm going to close this issue - I think it's more a question about the packaging standards & ecosystems more broadly, rather than Flit by itself.
