### ISSUE TITLE
Warn about redundant license field if classifier is present

### ISSUE THREAD

**Issue by merwok** [pypa/flit#465]
Projects are supposed to use a license classifier, if one exists for their license.
The `license` field is meant to be free-form text to specify a non-standard license or to add details to a classifier (to specify `Other :: Proprietary`, or maybe to add patent note for example).
Many projects needlessly define `license`, `flit` could warn about that when it validates metadata.

**Comment by takluyver** [comment]
I've also noticed that a lot of people set both, or prefer the license field. But at some point, it seems likely that it will be possible to express richer & more detailed license information in the license field as SPDX expressions ([PEP 639](https://www.python.org/dev/peps/pep-0639/)). So I don't want to push people too much towards classifiers for license information, when we might be pushing them in another direction in a few months.

**Comment by Conchylicultor** [comment]
A similar point could be made for the `requires-python` field.

With poetry, `"Programming Language :: Python :: 3",` and `"License :: OSI Approved :: Apache Software License"` classifiers are automatically set.

Maybe Flit could do the same ?

This would push people to use `license=` and `requires-python` fields rather than classifiers.

**Comment by pradyunsg** [comment]
I don't think we should add such a warning for `license`. Rather, I think that we should not do anything here. Also https://github.com/pypa/trove-classifiers/issues/17, which is about how existing license classifiers are not sufficeint.

Once PEP 639 is accepted, we'll deprecate both the license classifiers as well as the regular table-based license fields. Basically, we're going to get `license = "MIT"` once that happens and will want to push users to adopt that.

**Comment by merwok** [comment]
Let’s see where the PEP goes.
