### ISSUE TITLE
Access to readthedocs ?

### ISSUE THREAD

**Issue by Carreau** [pypa/flit#479]
I realized I don't have access to readthedocs, and I'm guessing we should give access to a few people from pypa in case something wrong happens.

**Comment by takluyver** [comment]
I've given you access on RTD and on PyPI. I asked on [the Discourse thread](https://discuss.python.org/t/should-flit-become-a-pypa-project/11854/13) if any other existing PyPA members wanted commit rights - so far no-one has contacted me about it.

**Comment by takluyver** [comment]
@pradyunsg and @gaborbernat were both interested in helping to maintain Flit, so I've added them on Github, RTD and PyPI.
