### ISSUE TITLE
Rename the default branch to `main`

### ISSUE THREAD

**Issue by DiddiLeija** [pypa/flit#484]
Hi everybody!

I know this project has just entered to the PyPA umbrella, and I'm happy to see that :smiley:! However, many PyPA repos have changed their default branch to `main`. For sanity reasons, can this project do the same?

**Comment by takluyver** [comment]
Yup, makes sense. Consistency is good, whatever people think about the actual words. I've done the rename.

Anyone who has the repository already cloned will likely need to update it. These are the command Github suggests:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by DiddiLeija** [comment]
Thanks @takluyver! I'm gonna close this. You may want to pin this issue, though :wink:.

**Comment by takluyver** [comment]
Thanks. I'll leave it pinned for a couple of weeks.
