### ISSUE TITLE
can `flit` handle / install multiple packages?

### ISSUE THREAD

**Issue by NickleDave** [pypa/flit#497]
Sorry if this is answered somewhere in docs or previous issues and I'm just not using the right terms to find it.

I have a project set up like this:
```
src
├── crowsetta
└── textgrid
```

The package `crowsetta` imports `textgrid`.    
I guess the technical term is "vendored"?  
I am not trying to do anything like a monorepo with multiple separate packages each in their own directory.
 
With a fancypants tool like `poetry` I am able to do this:
```toml
packages = [
    { include = "crowsetta", from = "src" },
    { include = "textgrid", from = "src" },
]
```
and when I run `poetry install` then they are both just there.

Is there a way to tell `flit` to install both `crowsetta` and `textgrid` or is that considered out of scope?  
Again I'm sorry I don't know the right way to describe what I'm doing.

**Comment by pradyunsg** [comment]
> Is there a way to tell `flit` to install both `crowsetta` and `textgrid` or is that considered out of scope?

There is no way to do that; and yes, it is considered out of scope.

**Comment by takluyver** [comment]
Yup, as @pradyunsg says, Flit is limited to a single top-level package. You can have multiple submodules and subpackages within that, e.g.

```
src
└── crowsetta
  ├── __init__.py
  └── textgrid.py
```

This pattern is common even if you're vendoring a package from someone else. E.g. pip [contains vendored modules](https://github.com/pypa/pip/tree/main/src/pip/_vendor) which it imports at paths like `pip._vendor.colorama`.

**Comment by NickleDave** [comment]
Thank you @pradyunsg and @takluyver 

Ah of course, I should use a sub-package to vendor.

I did find previous issues related to `pip` vendoring, but couldn't immediately see how `pip` was doing it.
Obviously I should've read the code a little closer, `_vendor` seems pretty explicit.

Appreciate it!
Closing

**Comment by emirkmo** [comment]
I couldn't find any documentation on this, but if I have multiple sub-modules as shown in @takluyver 's comment above, is there anything I need to specify in the `pyproject.toml` for them to be picked up? Akin to `find_packages` from `setuptools`?
