### ISSUE TITLE
Install into current environment by default, instead of environment that flit is installed in

### ISSUE THREAD

**Issue by NiklasRosenstein** [pypa/flit#504]
When installing a package with `flit install`, it will install the package in the site packages of the interpreter that is running flit. But when working with virtual environments, this becomes an easy source for error because you would need to explicitly specify it (for example with `--python python`) when that is reasonable default behaviour.

I would like to propose that, if a virtual environment is active, flit by default install into that environment instead of that of the interpreter that is running flit.

**Comment by takluyver** [comment]
As a workaround, note that you can also now `pip install .` for packages using Flit. `flit install` dates from before this worked, and it may go away at some point (I haven't entirely decided yet).

**Comment by NiklasRosenstein** [comment]
Thanks @takluyver , this works.
