### ISSUE TITLE
Help - why isn't description being picked up in pypi?

### ISSUE THREAD

**Issue by dougransom** [pypa/flit#508]
No description is picked up in the project when uploaded to pypi.

https://pypi.org/project/pandas_dataframe_convert/

relevant files:

https://github.com/dougransom/pandas_dataframe_convert/blob/main/pyproject.toml

https://github.com/dougransom/pandas_dataframe_convert/blob/main/src/pandas_dataframe_convert/__init__.py

**Comment by takluyver** [comment]
The terminology gets a bit mixed up. The 'description' in the PEP 621 metadata (which you've specified should be found dynamically) is the single line "pandas_dataframe_convert is a package to convert Pandas dataframes to other formats." This  has appeared on PyPI. The 'project description' which you're missing on PyPI comes from the `readme` key in `pyproject.toml`, which should point to your README file.

Note also that you've mis-spelled `dependencies` as `dependancies`. We're discussing making it error on unrecognised keys in #505 and #506.

**Comment by takluyver** [comment]
I see it's working now. :slightly_smiling_face:
