### ISSUE TITLE
Packaging py.typed

### ISSUE THREAD

**Issue by dycw** [pypa/flit#520]
Hi, as a former [`poetry`](https://github.com/python-poetry/poetry) user, I have been accustomed to packaging a `py.typed` marker as follows:

```
include = ["src/my_package/py.typed"]
```

I am wondering what is the equivalent protocol for `flit` users?

**Comment by pradyunsg** [comment]
As long as you have `py.typed` in your VCS-tracked-files, you shouldn't need to add any additional declarations.

See https://flit.readthedocs.io/en/latest/pyproject_toml.html#sdist-section for more details.

**Comment by dycw** [comment]
Thank you; closing as there is nothing else to add here.
