### ISSUE TITLE
flit install should not install optional dependencies by default

### ISSUE THREAD

**Issue by mardukbp** [pypa/flit#532]
According to the [documentation](https://flit.readthedocs.io/en/latest/cmdline.html#flit-install), `flit install` assumes by default `--deps all`. This is unexpected and runs counter to both the meaning of optional dependencies and "explicit is better than implicit". The user should not have to be explicit about restricting which dependencies are installed, but rather be explicit about installing extra dependencies.

**Comment by Carreau** [comment]
Arguably, `flit install` should only be used by someone who is trying to develop flit from the git repo, and it is common to have development install use more dependencies than releases.

I see your point, but at the same time that will in many case make `flit install` seem to not work.

**Comment by mardukbp** [comment]
You are right. I was using flit incorrectly.
