### ISSUE TITLE
Add --outdir to flit_core/build_dists.py

### ISSUE THREAD

**Issue by rossburton** [pypa/flit#533]
It would be useful for distributors (specifically, me) if `flit_core/build_dists.py` exposed the option to set the directory where the binaries should be written.

**Comment by pradyunsg** [comment]
Is doing an `mv` afterward difficult? I'm slightly wary of adding knobs to something that is purely intended to be for bootstrapping.

**Comment by takluyver** [comment]
You can also now use `python -m flit_core.wheel` (as described in the [bootstrapping doc](https://flit.readthedocs.io/en/latest/bootstrap.html)), which does have a `--outdir` option. Downstream distributors I know about generally start from an sdist (`.tar.gz` package), so I assume there's less need to create one of those.

**Comment by rossburton** [comment]
Ah, that's useful, thanks.  I'll close this as that's a good alternative.
