### ISSUE TITLE
`flit build` omits modified files tracked by mercurial

### ISSUE THREAD

**Issue by mwchase** [pypa/flit#539]
I have a project that's using mercurial for version tracking. If I change a source file and run `flit build`, the output starts with `Found 123 files tracked in hg`, and the changed file is not present in the generated artifacts. If I revert or commit the change, then `flit build` reports `Found 124 files tracked in hg` and the file is present.

I think this is because https://github.com/pypa/flit/blob/main/flit/vcs/hg.py#L24 doesn't have `"--modified"`.
Experimentally, the command from https://github.com/pypa/flit/blob/main/flit/vcs/git.py#L7 does not omit files that have changed.

**Comment by takluyver** [comment]
I think your diagnosis is correct. Obviously the mercurial integration is much less battle-tested than the git one. Do you want to make a PR?

**Comment by takluyver** [comment]
Closed by #541
