### ISSUE TITLE
setuptools setup.py

### ISSUE THREAD

**Issue by necrose99** [pypa/flit#547]
[setup.py.txt](https://github.com/pypa/flit/files/8597463/setup.py.txt)
[requirements.txt](https://github.com/pypa/flit/files/8597464/requirements.txt)
might be a means of just using the project.toml file insted... 

dev-python/flit_core-3.7.1::gentoo  USE="-test" PYTHON_TARGETS="pypy3* python3_8 python3_9 python3_10" 0 KiB
pip is USER only outside the fakeroot build system... 

All uses Except pypy3 are ok...   pypy3 -m pip install flit --user $"me" packages wheel just fine..

anyways if a user has "**YE Crufty setuptools**" gets bit aggravating  to safely update setuptools/sometimes  per instance of python as FLIT is now a core depend.. 
I'm just grinning in glee **not** , as my desktop install moved case mobo , parts shortages :-(  by the time i bring up to date... 

**IE python setup.py install as a legacy /emergency Fall back ...**   which in some cases / boot strapping might be of use... 
ie get flit installed so setuptools etc will update without breakage.. or in chroot/s /fakeroots not flake out... 

classically setup.py based ebuilds just  tend to work ....

**Comment by takluyver** [comment]
It's not very clear what you're asking or suggesting here, and I don't know anything really about Gentoo's build system, but there is a bootstrapping story that doesn't rely on setuptools or a `setup.py` file as a starting point: https://flit.pypa.io/en/latest/bootstrap.html
