### ISSUE TITLE
Add support to install dependencies from code repository

### ISSUE THREAD

**Issue by bbgw** [pypa/flit#555]
### Phenomena
Migrating from `requirements.txt`
```txt
pandas
"git+https://github.com/a_project/a_repo.git"
```
to `pyproject.toml` and using **Flit**:
```
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "a_project"
dependencies = [
    "pandas",
    "git+https://github.com/a_project/a_repo.git"
]
```

With the above illustrated `pyproject.toml`, `flit build` results in error reading:

```bash
$ flit build
Could not parse requirement: 'git+https://github.com/a_project/a_repo.git'  E-flit.validate
Config error: Invalid config values (see log)
```

### Expected Behavior
Expects dependency installation works, being consistent with `pip` install from a `requirements.txt`.

### Reference
[`pip install` dependencies from VCS](https://pip.pypa.io/en/stable/topics/vcs-support/#vcs-support)

**Comment by bbgw** [comment]
Figured it out and closing off the issue.

For anyone here, the problem is with the dependency format. (See [StackOverflow](https://stackoverflow.com/a/54794506/2272172)):
```
a_repo_pkgname @ git+https://github.com/a_project/a_repo.git
```

**Comment by palao** [comment]
Indeed it works for `flit build`. But it fails for `flit publish`:
```
requests.exceptions.HTTPError: 400 Client Error: Invalid value for requires_dist. Error: Can't have direct dependency: 'a_repo_pkgname @ git+https://github.com/a_project/a_repo.git' for url: https://upload.pypi.org/legacy/
```
Any idea?
