### ISSUE TITLE
What is the difference between flit install and pip install?

### ISSUE THREAD

**Issue by venthur** [pypa/flit#556]
What does the `flit install` provide that is not covered by `pip install`? As a developer i mainly care about `pip install -e .`, does it make a difference to use `flit install --symlink` or `pip` for that? 

Currently the documentation only says: 

> Install the package on your system.
>
> By default, the package is installed to the same Python environment that Flit itself is installed in; use [--python](https://flit.pypa.io/en/latest/cmdline.html#cmdoption-flit-install-python) or [FLIT_INSTALL_PYTHON](https://flit.pypa.io/en/latest/cmdline.html#envvar-FLIT_INSTALL_PYTHON) to override this.
>
> If you don’t have permission to modify the environment (e.g. the system Python on Linux), Flit may do a user install instead. Use the [--user](https://flit.pypa.io/en/latest/cmdline.html#cmdoption-flit-install-user) or [--env](https://flit.pypa.io/en/latest/cmdline.html#cmdoption-flit-install-env) flags to force this one way or the other, rather than letting Flit guess.

it would be nice to elaborate on the difference between `pip install` and `flit install` here.

**Comment by takluyver** [comment]
It's the same, except that `flit install --symlink` works in a slightly different way to `pip install -e .` (and a way that I happen to prefer).
