### ISSUE TITLE
Possibility to specify local copy of valid trove classifiers

### ISSUE THREAD

**Issue by AsgerAndersen** [pypa/flit#561]
I work on an offline machine, and I would like to use flit to build packages. When I run "flit build", it tries to fetch the list of valid trove classifiers from "'https://pypi.org/pypi?%3Aaction=list_classifiers'" (as far as I can see in the function "_download_and_read_classifiers" in the "flit/validate.py" module). This throws an error, since my machine is offline, and it means that it takes more time each time I run "flit build". Would it be possible to specify the path to a local copy of "https://pypi.org/pypi?%3Aaction=list_classifiers" or to turn off the request to retrieve the list of classifiers?

Thank you for your great work!

**Comment by takluyver** [comment]
It should fail gracefully in that scenario without you needing to do anything, by catching `ConnectionError`:

https://github.com/pypa/flit/blob/048c87c380ac41efc4b26222114e54f6581c64f6/flit/validate.py#L123-L129

If your system spends time trying to connect before failing, that probably indicates that something else is misconfigured - an actually offline machine should fail to connect straight away. But you can set the [FLIT_NO_NETWORK](https://flit.pypa.io/en/latest/cmdline.html#envvar-FLIT_NO_NETWORK) environment variable to tell it not to even try.

**Comment by AsgerAndersen** [comment]
Setting FLIT_NO_NETWORK to a non-empty value works - thanks for the answer!
