### ISSUE TITLE
Support for MANIFEST.in

### ISSUE THREAD

**Issue by jenstroeger** [pypa/flit#565]
Today I was surprised to learn that `flit` doesn’t support a [`MANIFEST.in`](https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute) file, but instead seems to mimic the `MANIFEST` in the [`[tool.flit.sdist]` section of the configuration](https://flit.pypa.io/en/latest/pyproject_toml.html#sdist-section) — i.e. no support for [glob](https://docs.python.org/3/library/glob.html)s.

However, that can become cumbersome when developing, because currently [my `MANIFEST.in`](https://github.com/jenstroeger/python-package-template/blob/66347c69af6dd9c30b2b85ebe022d2844573faee/MANIFEST.in#L2) does contain globs like<sup>†</sup>
```
recursive-exclude src/package/**/__pycache__ *
```
Other private packages contain similar lines.

**Question**: is there a plan to support `MANIFEST.in` files<sup>‡</sup>, i.e. read them and expand them in place of the `[tool.flit.sdist]` section?

—————
<sup>†</sup> Which is not in the VCS, I realize, but still serves as an example.
<sup>‡</sup> Checkers like [mgedmin/check-manifest](https://github.com/mgedmin/check-manifest) would continue to be useful, too.

**Comment by takluyver** [comment]
I find the `MANIFEST.in` syntax clumsy and hard to remember, so it was a deliberate decision from when I first started Flit to get away from that. As such, it's not on the roadmap to support.

The include & exclude lists in `[tool.flit.sdist]` *do* support globs, albeit not yet recursive globs. There's a PR (#550) which would add recursive globbing. All `__pycache__` folders should automatically be excluded by default without you needing to configure anything, though.

**Comment by jenstroeger** [comment]
Thank you @takluyver! I think with recursive globbing my scenarios would be addressed nicely. Looks like that PR may merge soon?
