### ISSUE TITLE
Feature requests for bootstrap install

### ISSUE THREAD

**Issue by nanonyme** [pypa/flit#570]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/python3-flit-core.bst#L14-17 is how we use this right now. (this is real meta distro usage of flit in real bootstrap scenario starting from plain Python). Any chance we could have following:
1. Prefix given as parameter (this is quite common that distros install under a prefix before creating a package)
2. Python bytecode compilation (optional?). Parameter could be eg -o given multiple times perhaps defaulting to current if none is given

It would allow getting rid of the boilerplate around calling the installer.

**Comment by nanonyme** [comment]
Tested briefly and it looks like the platlib vs purelib difference doesn't matter for us. Prefix does. Our root is immutable during build except for very specific locations.

**Comment by nanonyme** [comment]
Hm, also installer needs to create the destination directory with os.makedirs(path, exist_ok=True) if prefix is given. It most likely does not.

**Comment by nanonyme** [comment]
Please do not call compileall with concurrency, it may break reproducible buils.

**Comment by takluyver** [comment]
I'd really like to keep the bootstrap script as simple as possible, and leave e.g. byte compilation up to the caller to invoke separately.

In particular, there are [quite a few options](https://docs.python.org/3/library/compileall.html) for producing the .pyc files, and if the bootstrap install script calls this for you, it probably needs to re-expose quite a few of those, which builds further complexity.

To be honest, your four line snippet looks like pretty much what I'm expecting distros to do. It's a shame that there isn't a shorter way to get the purelib/platlib directory at the command line, but it's still a one liner. We could probably do the `mkdir -p` step inside the bootstrap script, which would save you one line.

I'll copy the snippet here for reference, in case it changes in the future:

```shell
PLATLIB=$(python -c "print(__import__('sysconfig').get_path('platlib'))")
mkdir -p %{install-root}$PLATLIB
python bootstrap_install.py dist/*.whl --installdir %{install-root}$PLATLIB
python3 -m compileall -o 0 -o 1 -o 2 "%{install-root}$PLATLIB"
```

**Comment by nanonyme** [comment]
I think this is fine. So essentially now the minimal amount of boilerplate is
```
cd flit_core
python3 -mflit_core.whel
python3 bootstrap_install.py dist/*.whl --install-root ${install-root}
python3 -m compileall -o 0 -o 1 --o 2 ${install-root}
```
