### ISSUE TITLE
Change name of published package

### ISSUE THREAD

**Issue by alexreg** [pypa/flit#578]
I see the following in the documentation.

```
Flit packages a single importable module or package at a time, using the import
name as the name on PyPI. All subpackages and data files within a package are
included automatically.
```

Is there any way to change the name of the package on PyPI without changing the name of the installed package / import name?

If not, this would be a handy feature to add.

**Comment by pradyunsg** [comment]
Hiya! This is indeed possible. See https://flit.pypa.io/en/latest/pyproject_toml.html#module-section

**Comment by alexreg** [comment]
Thank you. Might be nice to clarify that "installation name" = "name on PyPI", but glad to know anyway.
