### ISSUE TITLE
src layout with package not in name of project

### ISSUE THREAD

**Issue by MalcolmMielle** [pypa/flit#582]
Hi and thanks for the great package manager.

If I have a src folder with three modules: t1, t2 and t3, and I name my project "a_project" in `pyproject.toml`, I have an error: `ValueError: No file/folder found for module a_project`. Is that intended behavior?

For now the only solution I found is to have an empty folder named `a_project` with just a `__init__.py` file in it to be able to install all modules.

**Comment by takluyver** [comment]
That is intended behaviour, I'm afraid, and your solution probably won't work as well as it seems. Flit is designed to package a single top-level package, so in that scenario you should put t1, t2, t3 inside your `a_project` folder and import them them `from a_project import t1` (or `from a_project.t1 import something`). Within the package, you can also use relative imports (`from . import t1`).

Your package (the `a_project` folder) is allowed to have a different name from the distribution (what you `pip install`) - see https://flit.pypa.io/en/latest/pyproject_toml.html#module-section for that.
