### ISSUE TITLE
Build a package without vcs

### ISSUE THREAD

**Issue by dougransom** [pypa/flit#587]
I have a project that builds python extensions (.pyd binary files) which need to be installed in the same folder as python files.  The build attempte to to make a wheel using flit from those binaries.

The problem is flit requires the .pyd files to be staged in git, which I don’t wish to do.  

Any suggestions for a workaround??

**Comment by pradyunsg** [comment]
If you have a project that builds Python extensions, flit isn't the right tool for you. You'll want to use a different build backends that are designed to support that use case, like https://github.com/scikit-build/scikit-build or https://pypi.org/project/meson-python/ or https://github.com/pypa/setuptools.

**Comment by eli-schwartz** [comment]
I wonder how this is supposed to work anyway, do you want to have to manually run a Makefile before running flit?

Do you want to be able to run `pip install` with an sdist (for example via PyPI)?

**Comment by dougransom** [comment]
Yea i have a cmake build that produces the two pyd files and i need them installed in the same folder as  the python files.  

they will be installed with something like

`pip install ./mywheel.whl` .

Don’t plan to distribute an sdist.

**Comment by eli-schwartz** [comment]
Then it sounds like scikit-build would be a great fit for you?

**Comment by dougransom** [comment]
sci-kit builds looks like 3 steps back to setuptools. 

I think i’ll just script staging my binaries with git as part of the build process to trick flit into making my wheel.  Or use .gitignore on them if that works.

**Comment by dougransom** [comment]
It turned out if I put just include the build targets in .gitignore, they  are still included in the wheel made by flit, so that completel y worked.
