### ISSUE TITLE
multiple package workaround

### ISSUE THREAD

**Issue by WolfgangFahl** [pypa/flit#590]
I am coming from setup tools where in setup.py i may have entries such as:
```
packages=['ormigrate','ormigrate.smw','openresearch',''],
package_data={'ormigrate': ['resources/*.json','resources/*.yaml','resources/templates/**/*.jinja','resources/topics/*.json']},
```
which allows to specify multiple packages and resources which should endup in a release. 

It's all been very awkward to find out how this works and was never straightforward and hard to understand.

i love the approach of having a pyproject.toml file and since i started being a maintainer of justpy we have setup the build process using

https://github.com/justpy-org/justpy/blob/master/pyproject.toml

unfortunately we also have the discussions https://github.com/justpy-org/justpy/discussions/486
where the
```python
from .justpy import *
```
is giving us headaches for how to handling the jp namespace that was recommended in some 150 tutorial examples where the single line:
```python
import justpy as jp
```
is prominent and imports some 460 namespace entries.

Now we want to improve the situation see 

https://github.com/justpy-org/justpy/issues/498

and we started adding a new package/namespace https://github.com/justpy-org/justpy/tree/master/jpcore

unfortunately we do not see how this can be a subpackage due the import * issue.

We'd love to simply supply multiple packages with the jp prefix such as jpcore, jpconfig and so on to work around the problem.
Given the comments in #252, #497 and other issues it looks like flit is not designed to support our usecase.

**What workaround would there be?
If there is none what other build system would be fullfilling our needs?**

**Comment by takluyver** [comment]
Sorry, as you saw, Flit is designed around shipping a single top-level package (what you import) in each distribution (what you install). You can have arbitrary modules and subpackages inside that, but Flit doesn't support putting multiple top-level packages together.

There are a lot of different build systems trying out different things at the moment. I think even setuptools is gaining the ability to use `pyproject.toml` files. Other options I'm aware of include [Poetry](https://python-poetry.org/), [Hatch](https://hatch.pypa.io/latest/) and [PDM](https://pdm.fming.dev/latest/). They all do somewhat more than Flit.

**Comment by ofek** [comment]
For Hatch you [could](https://hatch.pypa.io/latest/config/build/#packages) do:

```toml
[tool.hatch.build.targets.wheel]
packages = [
  "src/pkg1",
  "src/pkg2",
  "src/pkg3",
]
```

**Comment by WolfgangFahl** [comment]
@ofek thanks thats the workaround i was looking for - i'll migrate to hatch then
