### ISSUE TITLE
 [project.optional-dependencies] - not picking up an extra.

### ISSUE THREAD

**Issue by dougransom** [pypa/flit#592]
Getting this warning 
`
PS C:\Users\Doug\dictation toolbox\dtactions> pip install dtactions[natlink_test]
Defaulting to user installation because normal site-packages is not writeable
Collecting dtactions[natlink_test]
  Downloading dtactions-1.5.3-py3-none-any.whl (196 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.6/196.6 kB 3.0 MB/s eta 0:00:00
WARNING: dtactions 1.5.3 does not provide the extra 'natlink_test'
`

`PS C:\Users\Doug\dictation toolbox\dtactions> flit --version
Flit 3.7.1`

`
From pyproject.toml

`[project.optional-dependencies]
test = [
    "pytest >=7.1.2",
]
#for tests that require natlink.

natlink_test = [ 
		"natlink",
]
dev = [
	"pyenvutils",
	"flit"
]`

`pip install .\dist\dtactions-1.5.2.tar.gz[test]` works fine.

Full pyproject.toml  https://github.com/dougransom/dtactions/blob/master/pyproject.toml

**Comment by takluyver** [comment]
When you `pip install dtactions[natlink_test]`, it's downloading the released version of dtactions from PyPI, which doesn't have the `natlink_test` extra. It looks like you added this in a PR https://github.com/dictation-toolbox/dtactions/pull/3 that hasn't been merged yet. So I think this is behaving as I'd expect.
