### ISSUE TITLE
How to add private repositories in pyproject.toml?

### ISSUE THREAD

**Issue by ttti07** [pypa/flit#594]
In poetry, we can add private repositories in pyproject.toml
https://python-poetry.org/docs/pyproject/#dependencies-and-dependency-groups

Is there any way in flit that corresponding to the feature above?

**Comment by takluyver** [comment]
Not exactly, no. Flit doesn't handle finding dependencies itself, so it supports only the standardised dependency metadata defined in [PEP 508](https://peps.python.org/pep-0508/), with which you can specify either a range of acceptable versions or a URL to one specific downloadable package.

You can give a tool like pip an index URL to search with either the `--index-url` or `--extra-index-url` options, but this will affect all packages it tries to find (dependencies and their dependencies).
