### ISSUE TITLE
How can flit consume packages from Azure DevOps 

### ISSUE THREAD

**Issue by vincferr** [pypa/flit#595]
For our project we are trying to migrate the build  system from `setup.py` to something TOML based.

Everything is working fine on the Azure DevOps pipeline and locally as well, as long packages on pypi are consumed by the project.

The process breaks when we need to consume our private packages, stored in our Azure.

Usually, to allow our virtual environment to consume our private packages, we create locally a `pip.ini` file:

https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-cli?view=azure-devops

How can we pass such specification to the virtual environment used by flit to build the package?

**Comment by takluyver** [comment]
I hope between us we've covered this, so I'll close the issue, but that doesn't prevent further comments if needed.
