### ISSUE TITLE
Another flit wrapper; wondering about the need to stub dynamic=

### ISSUE THREAD

**Issue by prof-milki** [pypa/flit#605]
> `type: q&a`  
> `priority: low`  
> `flit-ver: 3.7.1`

So, this might be a bit off-topic. And [packaging-discuss](https://discuss.python.org/c/packaging/14) could be a better avenue, if I could make it more concrete. Anyway: Just built a little flit wrapper to migrate my old setup.py use from. And **flit** already happens to make quite a difference performance-wise!

![flit - can't believe it's not setup.py!!](https://i.imgur.com/82cTkcq.gif)

It also turns out to be less code → [pluginconf/flit.py](https://fossil.include-once.org/pluginspec/file/pluginconf/flit.py) than the old setup() parameter fiddling. But I'm using a kind of more intrusive monkeypatching approach than e.g. flit_scm.
It does work. But it's also sort of lazy:

```python
@inject(flit_core.config)
def read_flit_config(path):
    …

@inject(flit_core.common)
def make_metadata(module, ini_info):
    …
```

Which looked less effort than reimplementing `prepare_metadata_for_build_wheel()`. But of course neither is an official extension API - and that's of course out of scope for flit.

 * Thus I'm wondering if that's the easiest or most likely stable interface to tinker with. (Not asking for this fringe use case impairing any future development of flit, of course.)
 * The original `make_metadata()` seems kinda slim, and somewhat elaborate in my override.  But it's quite convenient to have the parsed toml and module infos at hand.
 * Overriding `read_flit_config()` however could be kinda redundant, if there's no  `pyproject.toml` compatibility needs. It's a bit of a development-stage conundrum I ran into:

## Why is dynamic= ?

Only got some surface understanding of the various packaging PEPs. But figured the requirement for flit erroring out over generous `dynamic=[…]` entries stems from [declaring-project-metadata](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#dynamic). Which I ran into when testing setuptools` and flit alternatively, and trying to avert setup() warnings. - Flit only supports two fields, but setuptools currently insists on enlisting the whole swath of potentially dynamic fields.

Kinda fixed it now by virtue of fixating the toml values in the overriden `read_flit_config()`. But I'm now wondering why pyproject.toml required a `dynamic=` field to begin with. It appears to me this makes build backends less interchangeable, not more. Obviously my use case specifically wants to avert centralizing meta data - so quite the opposite of pyproject.
But I'm not sure there's much benefit to not inferring dynamicness of fields= from their absence in `[project]`. And thus defaulting on error messages in such cases. Haven't found much hints on why or how this would improve build consistency, TBH.

**Comment by pradyunsg** [comment]
> But I'm now wondering why pyproject.toml required a `dynamic=` field to begin with. It appears to me this makes build backends less interchangeable, not more.

Certain metadata cannot be statically written in a source tree and to allow for build-backends to have their own discovery logic.

For example, [`hatch-vcs`](https://github.com/ofek/hatch-vcs/blob/4f876cd8719a6e4e34063a29a916f7a654dcba1f/pyproject.toml#L38) uses `dynamic = <version>` to locate the tooling for building distributions. Flit uses dynamic version/description to locate the version/description from the user's source code.

Having an explicit list of things that have invalid metadata means that installers like pip can know whether to warn or error out on inconsistent matadata and whether they can rely on metadata provided by a source distribution.

**Comment by prof-milki** [comment]
> Having an explicit list of things that have invalid metadata means that installers like pip can know whether to warn or error out on inconsistent matadata […]

Thanks. And that totally makes sense for build reproducibility, if dynamic= connotates the a requirement for sourcing. I think I'm having not enough overview of backend variations and when such overlap cases might arise (binary builds?).

I guess my question is less about explicating the source, but why there isn't an implicit default (e.g. pyproject.toml always supersedes dynamic values) and a warning instead of mandated errors. Though of course, it's a fringe worry when you just had to update project.dynamic= for swapping tools. (Just trying to figure out if I can avert `patch_flit_config()`. I think FLIT_ALLOW_INVALID seems to broad.)

---

Btw, anyone considered including a man page in data files? `pandoc cmdline.rst --standalone -f markdown+pandoc_title_block --to man > flit.1` (might need markdown per-conversion though.)

**Comment by pradyunsg** [comment]
> why there isn't an implicit default (e.g. pyproject.toml always supersedes dynamic values) and a warning instead of mandated errors.

Because then there would be seemingly two sources of truth and users would need to investigate why updating it in their `__init__.py` file isn't resulting in a different version of the package (eg: in your workflow, the `pyproject.toml` version would take precedence, and it'd be a warning; except that warnings are suppressed when pip performs a build).

**Comment by prof-milki** [comment]
Ah, thanks again. I was completely oblivious to the nested build tool usage. That pretty much explains the mandatory erroring out.

**Comment by pradyunsg** [comment]
Closing this out, since it seems all your questions have been answered. :)

**Comment by takluyver** [comment]
Also, just to re-emphasise: the only Python API that you should rely on from Flit is the backend API specified by [PEP 517](https://peps.python.org/pep-0517/), [PEP 660](https://peps.python.org/pep-0660/) and any future follow-up PEPs when they're implemented. This is available as the module `flit_core.buildapi`.

Any other Python functions or classes should be seen as implementation, and they may change with no warning. If you're playing around with it for your own use, you can do whatever you like, but if you're building a tool and encouraging others to use it, it's best not to rely on undocumented APIs - doubly so if you're monkeypatching functions and relying on them being called. I'd rather not have to put everything in an `_internal` subpackage like pip has, but that's an option if necessary.

(Hopefully you know this already, but I wanted to leave a note for anyone else reading)
