### ISSUE TITLE
Provide a description for `flit-core` on PyPI

### ISSUE THREAD

**Issue by scdub** [pypa/flit#612]
I noticed `flit-core` as a new dependency of `typing_extensions` 4.4.0. Wanting to see what this package is, I headed over [to the PyPI page](https://pypi.org/project/flit-core/) but got the somewhat ominous "The author of this package has not provided a project description" on that page. Of course, reading it and seeing the subtitle along with the links it isn't hard to figure out, but would be nice to have a description of `flit-core` directly on PyPI for upstream packages which use the core package for their build backend.

**Comment by takluyver** [comment]
Makes sense. I think after various other changes, if we list the README file in the appropriate place in its `pyproject.toml`, that should just work. Do you want to make a PR?
