### ISSUE TITLE
Use custom build wheel packages

### ISSUE THREAD

**Issue by svartkanin** [pypa/flit#627]
Is there a way to add locally custom build wheel packages to the dependencies? 

I have a 3rd party package that is not published to PyPi therefore installing it from there isn't an option.

**Comment by takluyver** [comment]
The usual way to do this is to specify `--index-url` or `--extra-index-url` to pip when installing the package (if you use `--extra-index-url`, you should be aware of the possibility of dependency confusion attacks, where someone uploads a package with the same name on PyPI). 

There isn't really a good way to specify where a package should come from in the dependencies of a package itself. See this blog post on [concrete vs abstract requirements](https://caremad.io/posts/2013/07/setup-vs-requirement/) for more background on why things work that way.
