### ISSUE TITLE
Scripts installed only when an extra is installed

### ISSUE THREAD

**Issue by dougransom** [pypa/flit#629]
in `[project.scripts]`
is it possible to specify  to install a script only when an extra dependency is installed?

If so can that be included in the examples in the readme?

**Comment by takluyver** [comment]
No, that's not supported, sorry.

Entry points (including scripts) tagged with extras are not recommended, according to the [entry points spec](https://packaging.python.org/en/latest/specifications/entry-points/). Part of the reason for this is that there's no separate record of whether an extra is installed or not - if you install all the dependencies for an extra separately, tools can consider that extra to be installed, but scripts conditional on that extra may not be installed.
