### ISSUE TITLE
RECORD has incorrect file mode in generated archives

### ISSUE THREAD

**Issue by henryiii** [pypa/flit#634]
The file mode is incorrect for generated files:

```console
$ zipinfo dist/*.whl
...
?rw-r--r--  2.0 unx      104 b- defN 16-Jan-01 00:00 wheel-0.38.4.dist-info/entry_points.txt
-rw-r--r--  2.0 unx     1107 b- defN 23-Jan-27 13:33 wheel-0.38.4.dist-info/LICENSE.txt
?rw-r--r--  2.0 unx       81 b- defN 16-Jan-01 00:00 wheel-0.38.4.dist-info/WHEEL
?rw-r--r--  2.0 unx     2051 b- defN 16-Jan-01 00:00 wheel-0.38.4.dist-info/METADATA
?rw-r--r--  2.0 unx     2747 b- defN 16-Jan-01 00:00 wheel-0.38.4.dist-info/RECORD
```

Notice the file flag is `?` for all the generated files - `stat.S_IFREG` is not being set.

See https://github.com/pypa/wheel/issues/506, where this was just fixed in `wheel` (though it only had an issue with `RECORD`, while flit-core has this for more files). The fix was in https://github.com/pypa/wheel/pull/511. It should be fairly straightforward to apply the same fix here - `0o664 | stat.S_IFREG` should be used instead of 0o664 here: https://github.com/pypa/flit/blob/532bdaabafe0660b6c7494d8043ec4fa15b286a8/flit_core/flit_core/wheel.py#L140
Or it should be or'd in later, like when this function is called or inside this function: https://github.com/pypa/flit/blob/532bdaabafe0660b6c7494d8043ec4fa15b286a8/flit_core/flit_core/wheel.py#L35-L37
Actually, that function has a comment about making it a regular file by setting an extra bit but literally doesn't do it (and not sure what `0xFFFF` mention is, it's 0x8000, and and'ing with `0xFFFF` is done elsewhere). So that's where it probably should be done. But then again, that function runs on the actual regular files too, but those should be already regular files.

This doesn't "break" anything as far as I know, it's just slightly ugly with the `?`'s and technically incorrect.

**Comment by henryiii** [comment]
I can make a PR if I know which of the three places the `| stat.S_IFREG` ideally should go. This isn't tested in tests, I checked by adding it to the `_set_zinfo_mode` function.

**Comment by takluyver** [comment]
I'd say it should go inside `_write_to_zip()`. That function always makes regular files, so there's no need for it to be part of a parameter (in fact it looks like the `mode=` parameter is unused anyway).

`_add_file` seems to be able to call `_set_zinfo_mode` on directories as well, so setting the 'regular file' bit inside that helper function could be wrong. At a glance, I think it might never be used on a regular file, but still.
