### ISSUE TITLE
`flit publish` fails with error `Unrecognised classifier`

### ISSUE THREAD

**Issue by sphuber** [pypa/flit#640]
I am publishing my package on Github actions using `flit publish`. This used to work fine (at least one month ago) but today the build failed with:
```
   flit publish
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.11/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.11/x64/lib
    FLIT_USERNAME: __token__
    FLIT_PASSWORD: ***
Fetching list of valid trove classifiers               I-flit.validate
Unrecognised classifier: 'Operating System :: MacOS :: MacOS X'  E-flit.validate
Unrecognised classifier: 'Operating System :: POSIX :: Linux'  E-flit.validate
Unrecognised classifier: 'Programming Language :: Python'  E-flit.validate
Unrecognised classifier: 'Programming Language :: Python :: 3.10'  E-flit.validate
Unrecognised classifier: 'Programming Language :: Python :: 3.11'  E-flit.validate
Unrecognised classifier: 'Programming Language :: Python :: 3.8'  E-flit.validate
Unrecognised classifier: 'Programming Language :: Python :: 3.9'  E-flit.validate
Unrecognised classifier: 'Topic :: Scientific/Engineering'  E-flit.validate
```
Now these classifiers haven't changed since the latest build that succeeded. Also, they are listed as valid classifiers by [PyPI](https://pypi.org/pypi?%3Aaction=list_classifiers). So what changed? Are they no longer considered valid by `flit` or is it a red-herring and is there another problem causing this?

**Comment by takluyver** [comment]
I'm not sure what could cause that. If you want to upload your package in the meantime, you might try setting [`FLIT_ALLOW_INVALID`](https://flit.pypa.io/en/stable/cmdline.html#envvar-FLIT_ALLOW_INVALID) to bypass the check.

**Comment by sphuber** [comment]
Thanks for the tip. I just happened to have run the workflow again for the latest release, and now it worked just fine. Again, the `pyproject.toml` was not touched. Let's chalk it up to some weird fluke and close this issue.

**Comment by takluyver** [comment]
Thanks, that makes sense. It could happen if for some reason https://pypi.org/pypi?%3Aaction=list_classifiers returns a success response with no content.
