### ISSUE TITLE
Missing runtime dependency on pip

### ISSUE THREAD

**Issue by stanislavlevin** [pypa/flit#646]
According to docs https://flit.pypa.io/en/stable/cmdline.html#flit-install:
> Flit calls pip to do the installation.

but `pip` is not specified as runtime dependency of `flit`.

**Comment by takluyver** [comment]
Hmmm, good point. I think I just assume `pip` is always present, which naturally is not really true. Do you want to make a PR?

**Comment by orsinium** [comment]
Project dependencies specify packages to be installed in the same environment as flit. However, flit currently uses pip installed in the target environment, which may be changed by passing `--python` flag. I'm going to change this behavior in #651 to make flit use pip from the flit's environment if available.
