### ISSUE TITLE
Tests missing from `flit_core-3.10.0` sdist (but not `flit-3.10.0`)

### ISSUE THREAD

**Issue by mgorny** [pypa/flit#703]
It seems that as part of the directory reorganization, `tests_core` directory is not included in 3.10.0 sdist for `flit_core`. However, complete `flit_core` along with `tests_core` is included in 3.10.0 sdist for `flit`. Could we also get tests included in `flit_core` sdist, please?

**Comment by takluyver** [comment]
Sorry about that, #704 should fix it.

I'll do a release once I've worked out if I need to change anything for #702 as well.

**Comment by mgorny** [comment]
Thanks!

Yeah, I've been waiting to see what comes out of that bug as well, before adding the new version to Gentoo.

**Comment by takluyver** [comment]
3.10.1 is out now with the tests included.
